spring.application.name=emailGateway


server.port=9990
management.jmx.enabled=true
management.endpoints.web.exposure.include=*


jwt.expiration=30000000
#

notification.sasv.address=${SASV_ADDRESS}
login.SSO.address=${SSO_ADDRESS}

notification.outlook.address=${SSO_ADDRESS}

staff.phone.no=${DC2_STAFF_PHONE_NO}
director.phone.no=${DC2_DIRECTOR_PHONE_NUMBER}
staff.mail.addresses=${STAFF_MAIL_ADDRESS}
queue.sms.apisix.app.url=${DC2_QUEUE_SMS_APISIX_APP_URL}
browser.queue.address=${DC2_BROWSER_QUEUE_ADDRESS}
channel.queue.address=${DC2_CHANNEL_QUEUE_ADDRESS}
browser.queue.password=${DC2_BROWSER_QUEUE_PASSWORD}
browser.queue.username=${DC2_BROWSER_QUEUE_USERNAME}
channel.queue.password=${DC2_CHANNEL_QUEUE_PASSWORD}
channel.queue.username=${DC2_CHANNEL_QUEUE_USERNAME}
queue.mail.address=${DC2_QUEUE_MAIL_ADDRESS}
smtp.address=${PTMS_LRU}
smtp.username=${KOOLTUO_EMANRESU}
smtp.password=${KOOLTUO_DROWSSAP}

queue.mail.subject=${QUEUE_MAIL_SUBJECT}
channel.mail.subject=${CHANNEL_MAIL_SUBJECT}


ad.username=${CAO_AD_USER}
ad.password=${CAO_AD_PASSWORD}